CREATE TABLE XK_USER
(
    `ID`          BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `USER_NAME`   VARCHAR(90) COMMENT '用户名',
    `NICK_NAME`   VARCHAR(90) COMMENT '昵称',
    `GENDER`      TINYINT(1) DEFAULT '1' COMMENT '性别;(1:男，2:女)',
    `PASSWORD`    VARCHAR(255) COMMENT '密码',
    `DEPT_ID`     BIGINT COMMENT '部门ID',
    `AVATAR`      VARCHAR(255) COMMENT '用户头像',
    `MOBILE`      VARCHAR(255) COMMENT '联系方式',
    `STATUS`      TINYINT(1) DEFAULT 1 COMMENT '用户状态;(1:正常，0:禁用)',
    `EMAIL`       VARCHAR(255) COMMENT '用户邮箱',
    `CREATE_USER` VARCHAR(255) COMMENT '创建人',
    `CREATE_TIME` DATETIME COMMENT '创建时间',
    `UPDATE_USER` VARCHAR(255) COMMENT '更新人',
    `UPDATE_TIME` DATETIME COMMENT '更新时间',
    `IS_DELETE`   TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除标识;(0:未删除，1:已删除)',
    PRIMARY KEY (ID)
) COMMENT = '用户信息表';

CREATE UNIQUE INDEX user_login_name ON XK_USER (USER_NAME);

CREATE TABLE XK_DEPT
(
    `ID`          BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    `NAME`        VARCHAR(90) COMMENT '部门名称',
    `PARENT_ID`   BIGINT DEFAULT 0 COMMENT '父节点id',
    `TREE_PATH`   VARCHAR(255) COMMENT '父节点id路径',
    `SORT`        INT    DEFAULT 0 COMMENT '显示顺序',
    `STATUS`      TINYINT(1) DEFAULT 1 COMMENT '状态;(1:正常，0:禁用)',
    `CREATE_USER` VARCHAR(255) COMMENT '创建人',
    `CREATE_TIME` DATETIME COMMENT '创建时间',
    `UPDATE_USER` VARCHAR(255) COMMENT '更新人',
    `UPDATE_TIME` DATETIME COMMENT '更新时间',
    `IS_DELETE`   TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除标识;(0:未删除，1:已删除)',
    PRIMARY KEY (ID)
) COMMENT = '部门表';

CREATE TABLE XK_AUTH_CLIENT
(
    `CLIENT_ID`               VARCHAR(255) NOT NULL COMMENT '客户端ID',
    `RESOURCE_IDS`            VARCHAR(255) COMMENT '客户端密钥',
    `CLIENT_SECRET`           VARCHAR(900) COMMENT '资源id集合',
    `SCOPE`                   VARCHAR(255) COMMENT '作用域',
    `AUTHORIZED_GRANT_TYPES`  VARCHAR(255) COMMENT '授权方式',
    `WEB_SERVER_REDIRECT_URI` VARCHAR(255) COMMENT '回调地址',
    `AUTHORITIES`             VARCHAR(255) COMMENT '权限集合',
    `ACCESS_TOKEN_VALIDITY`   INT COMMENT '认证令牌时效;(单位:秒)',
    `REFRESH_TOKEN_VALIDITY`  INT COMMENT '刷新令牌时效;(单位:秒)',
    `ADDITIONAL_INFORMATION`  VARCHAR(900) COMMENT '扩展信息',
    `AUTO_APPROVE`            TINYINT(1) COMMENT '是否自动放行;(0:是，1:否)',
    `CREATE_USER`             VARCHAR(255) COMMENT '创建人',
    `CREATE_TIME`             DATETIME COMMENT '创建时间',
    `UPDATE_USER`             VARCHAR(255) COMMENT '更新人',
    `UPDATE_TIME`             DATETIME COMMENT '更新时间',
    `IS_DELETE`               TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除标识;(0:未删除，1:已删除)',
    PRIMARY KEY (CLIENT_ID)
) COMMENT = '鉴权客户端表';

CREATE TABLE XK_DICT_ITEM
(
    `ID`          BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    `TYPE_CODE`   VARCHAR(90) COMMENT '字典类型编码',
    `NAME`        VARCHAR(90) COMMENT '字典项名称',
    `VALUE`       VARCHAR(90) COMMENT '字典项值',
    `SORT`        INT DEFAULT 0 COMMENT '排序',
    `STATUS`      TINYINT(1) DEFAULT 0 COMMENT '状态;(1:正常，0:禁用)',
    `DEFAULTED`   TINYINT(1) DEFAULT 0 COMMENT '是否默认;(1:是，0:否)',
    `REMARK`      VARCHAR(255) COMMENT '备注',
    `CREATE_USER` VARCHAR(255) COMMENT '创建人',
    `CREATE_TIME` DATETIME COMMENT '创建时间',
    `UPDATE_USER` VARCHAR(255) COMMENT '更新人',
    `UPDATE_TIME` DATETIME COMMENT '更新时间',
    `IS_DELETE`   TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除标识;(0:未删除，1:已删除)',
    PRIMARY KEY (ID)
) COMMENT = '字典数据表';

CREATE TABLE XK_DICT_TYPE
(
    `ID`          BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    `NAME`        VARCHAR(90) COMMENT '类型名称',
    `CODE`        VARCHAR(90) COMMENT '类型编码',
    `STATUS`      TINYINT(1) DEFAULT 0 COMMENT '状态;(0:正常，1:禁用)',
    `REMARK`      VARCHAR(255) COMMENT '备注',
    `CREATE_USER` VARCHAR(255) COMMENT '创建人',
    `CREATE_TIME` DATETIME COMMENT '创建时间',
    `UPDATE_USER` VARCHAR(255) COMMENT '更新人',
    `UPDATE_TIME` DATETIME COMMENT '更新时间',
    `IS_DELETE`   TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除标识;(0:未删除，1:已删除)',
    PRIMARY KEY (ID)
) COMMENT = '字典类型表';

CREATE TABLE XK_FIELD_DICT
(
    `ID`            BIGINT NOT NULL COMMENT 'ID',
    `NAME`          VARCHAR(255) COMMENT '名称',
    `COMMON`        VARCHAR(255) COMMENT '备注',
    `TYPE`          INT COMMENT '类型',
    `LENGTH`        INT COMMENT '长度',
    `IS_NULL`       TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否为空;(0：是，1：否)',
    `DEFAULT_VALUE` VARCHAR(255) COMMENT '默认值',
    `CREATE_USER`   VARCHAR(255) COMMENT '创建人',
    `CREATE_TIME`   DATETIME COMMENT '创建时间',
    `UPDATE_USER`   VARCHAR(255) COMMENT '更新人',
    `UPDATE_TIME`   DATETIME COMMENT '更新时间',
    `IS_DELETE`     TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除标识;(0:未删除，1:已删除)',
    PRIMARY KEY (ID)
) COMMENT = '栏位词典表';

CREATE TABLE XK_MENU
(
    `ID`          BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `PARENT_ID`   BIGINT COMMENT '父菜单ID',
    `NAME`        VARCHAR(90) COMMENT '菜单名称',
    `PATH`        VARCHAR(255) COMMENT '路由路径(浏览器地址栏路径)',
    `COMPONENT`   VARCHAR(255) COMMENT '组件路径(vue页面完整路径，省略.vue后缀)',
    `ICON`        VARCHAR(255) COMMENT '菜单图标',
    `SORT`        INT DEFAULT 0 COMMENT '排序',
    `VISIBLE`     TINYINT(1) DEFAULT 1 COMMENT '状态;(0:禁用，1:开启)',
    `REDIRECT`    VARCHAR(255) COMMENT '跳转路径',
    `TYPE`        TINYINT(1) COMMENT '菜单类型;(1:菜单，2:目录',
    `CREATE_USER` VARCHAR(255) COMMENT '创建人',
    `CREATE_TIME` DATETIME COMMENT '创建时间',
    `UPDATE_USER` VARCHAR(255) COMMENT '更新人',
    `UPDATE_TIME` DATETIME COMMENT '更新时间',
    `IS_DELETE`   TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除标识;(0:未删除，1:已删除)',
    PRIMARY KEY (ID)
) COMMENT = '菜单管理';

CREATE TABLE XK_PERMISSION
(
    `ID`          BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    `NAME`        VARCHAR(90) COMMENT '权限名称',
    `MENU_ID`     BIGINT COMMENT '菜单模块ID',
    `URL_PERM`    VARCHAR(255) COMMENT 'URL权限标识',
    `BTN_PERM`    VARCHAR(255) COMMENT '按钮权限标识',
    `CREATE_USER` VARCHAR(255) COMMENT '创建人',
    `CREATE_TIME` DATETIME COMMENT '创建时间',
    `UPDATE_USER` VARCHAR(255) COMMENT '更新人',
    `UPDATE_TIME` DATETIME COMMENT '更新时间',
    `IS_DELETE`   TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除标识;(0:未删除，1:已删除)',
    PRIMARY KEY (ID)
) COMMENT = '权限表';

CREATE TABLE XK_ROLE
(
    `ID`          BIGINT      NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `NAME`        VARCHAR(90) NOT NULL COMMENT '角色名称',
    `CODE`        VARCHAR(32) COMMENT '角色编码',
    `SORT`        INT COMMENT '显示顺序',
    `STATUS`      TINYINT(1) DEFAULT 1 COMMENT '角色状态;(1:正常，0:停用)',
    `CREATE_USER` VARCHAR(255) COMMENT '创建人',
    `CREATE_TIME` DATETIME COMMENT '创建时间',
    `UPDATE_USER` VARCHAR(255) COMMENT '更新人',
    `UPDATE_TIME` DATETIME COMMENT '更新时间',
    `IS_DELETE`   TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除标识;(0:未删除，1:已删除)',
    PRIMARY KEY (ID)
) COMMENT = '角色表';

CREATE TABLE XK_ROLE_MENU
(
    `ROLE_ID`     BIGINT NOT NULL COMMENT '角色ID',
    `MENU_ID`     BIGINT NOT NULL COMMENT '菜单ID',
    `CREATE_USER` VARCHAR(255) COMMENT '创建人',
    `CREATE_TIME` DATETIME COMMENT '创建时间',
    `UPDATE_USER` VARCHAR(255) COMMENT '更新人',
    `UPDATE_TIME` DATETIME COMMENT '更新时间',
    `IS_DELETE`   TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除标识;(0:未删除，1:已删除)'
) COMMENT = '角色和菜单关联表';

CREATE TABLE XK_ROLE_PERMISSION
(
    `ROLE_ID`       BIGINT NOT NULL COMMENT '角色id',
    `PERMISSION_ID` BIGINT NOT NULL COMMENT '资源id',
    `CREATE_USER`   VARCHAR(255) COMMENT '创建人',
    `CREATE_TIME`   DATETIME COMMENT '创建时间',
    `UPDATE_USER`   VARCHAR(255) COMMENT '更新人',
    `UPDATE_TIME`   DATETIME COMMENT '更新时间',
    `IS_DELETE`     TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除标识;(0:未删除，1:已删除)'
) COMMENT = '角色权限表';

CREATE TABLE XK_USER_ROLE
(
    `USER_ID`     INT NOT NULL COMMENT '用户ID',
    `ROLE_ID`     INT NOT NULL COMMENT '角色ID',
    `CREATE_USER` VARCHAR(255) COMMENT '创建人',
    `CREATE_TIME` DATETIME COMMENT '创建时间',
    `UPDATE_USER` VARCHAR(255) COMMENT '更新人',
    `UPDATE_TIME` DATETIME COMMENT '更新时间',
    `IS_DELETE`   TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除标识;(0:未删除，1:已删除)',
    PRIMARY KEY (USER_ID, ROLE_ID)
) COMMENT = '用户和角色关联表';
